---
title: "Odds, logodds og ratio"
teaching: 42
exercises: 47
questions: 
- "Hvad er odds ratios?"
objectives:
- "Forstå det her nok til at vi kan hjælpe studerende"

keypoints:
- "FIXME"
source: Rmd
math: yes
---

```{r, include = FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("17-")

```

## Hvad er odds? 

Hvis du spiller på fodboldkampe og sådan noget - så kender du dem.

Odds er en anden måde at angive sandsynligheden for at noget sker.

Det er forholdet mellem at noget sker, og at noget ikke sker. Eksempelvis at hvis
FCK spiller 5 kampe mod Brøndby. Hvis vi mener at forholdene taler for at 
FCK vinder 1 kamp, og taber fire, er odds for at FCK vinder 1 til 4, eller:
$$\frac{1}{4}$$ Eller 0,25. 

Det er ikke det samme som sandsynligheder. Odds er forholdet mellem at noget sker
og noget ikke sker. Mens sandsynligheden er sandsynligheden for at noget sker, 
ud af alt hvad der kan ske. I eksemplet altså $$\frac{1}{5}$$ Eller 0,20.

Odds for at FCK vinder, er altså forskellig fra sandsynligheden for at FCK
vinder.

Er der en sammenhæng? Ja. Sandsynligheden for at FCK vinder er 0.2. Sandsynligheden
for at de taber er 1 - 0.2 = 0.8. 
Og sandsynligheden for at de vinder divideret med sandsynligheden for at de taber
er derfor:

$$\frac{0.2}{0.8} = 0.25$$

Det vil sige at vi kan beregne odds både ved at tælle. Men også ved at kigge på
sandsynligheden.

Man vil ofte se odds defineret som 

$$\frac{p}{1-p}$$, hvor p er sandsynligheden for at noget sker.

## Hvad er så log odds?
Odds for at FCK vinder er 1:4. Hvis FCK var et dårligere hold, ville odds måske være 
1:8 eller 1:42. Hvis odds taler for at FCK taber, ligger odds mellem 0 og 1. 

Men hvis odds i stedet taler for at FCK vinder, eksempelvis at vi forventer at de
vinder 4 gange ud af 5, vil odds være 4:1. Hvis de er endnu bedre, ville 
odds måske være 47:1. Det betyder at hvis odds taler for at FCK finder, vil
odds ligge mellem 1 og uendelig. 

Vi logaritmerer derfor for at få de to sæt af odds til at blive symmetriske.

det kan visualiseres eller noget. Eller i hvert fald forklares bedre.

log(odds) = log(5/3) = log(p/1-p) = log(1.7) = 0.53

Ret tal til så de matcher!

log(p/1-p) kaldes også logit-funktionen, og er fundamentet for logistisk regression.

Så. Odds er forholdet mellem noget der sker, og noget der ikke sker. Og log odds er
logaritmen af de odds.

log odds gør ting symmetriske, lettere at fortolke, og gør det muligt at lave
visse statistiske ting.

## Hvordan så med odds-ratio?

Selvom odds er en ratio, er det ikke det samme som odds-ratio.

Når vi taler om odds ratio, taler vi om en ratio mellem odds. 

FIND ET ANDET EKSEMPEL

cancer: ja mutation: ja 23 personer
cancer: nej, mutation: ja 117 personer
cancer ja, mutation ja: 6 personer
cancer nej, mutation nej 210 personer

Vi kan bruge en odds ratio til at afgøre (eller få en indikation af) om 
der er en sammenhæng mellem mutationen og canceren.

Hvis nogen har mutationen, er odds så højere for at de får cancer?

hvis en person har genet er odds for cancer: 23/117

Og hvis de ikke ahr genet, er4 odds for cancer 6/210

Vores odds-ratio er så: 23/117 / 6/210 = 0.2/0.03 = 6.88

så odds er 6,88 gange søtre for at en person med genet har cancer. 

log(6.88) = 1.93

de indikerer en sammenhægn mellem genet og cancer. Større værdier antyder at
genet er en god indikator for cancer. Små værdier at det er en dårlig indikator.

Er sammenhængen statistisk signifikant?

Det kan vi finde ud af på tre måder.

Fischer eksakt

chi^2

wald testen.

Og der er ikke enighed om hvilken der er bedst. de to første giver gerne en 
p-værdi og den sidste et konfidensinterval. Andre bruger wald testen til både
p-værdi go konfidensinterval.

personer med cancer - der er 29.
Uden cancer - der er 327 af.

hvad er p-værdien for at vi tilfældigt får 23 med og 117 uden cancer.
vi skal have styr på hvordan den faktisk beregnes. Facit er 0.00001

chi^2

sammenligner de observerede værdier med hvordan fordelingen ville være hvis der ikke var
en smamenhæng.
ialt har vi 356 personer, og 29 har cancer. Så sandsynligheden for at have
cancer er 0.08. Eftersom vi har 23+117 personer med genet, skal vi se 140*0.08 = 
11.2 personer med cancer. Det er det forventede antal personer med cancer og genet.

der er 216 personer uden genet. Der forventer vi 0.08*216 = 17.3 cancer tilfælde.

Nu sammenligner vi, og får en p-værdi med 0.00001. der er nogen korrektioner. Men

Wald-testen.

bruges ofte til at bestemme både signifikansen og konfidensintervaller.
Log af odds-ratio er normalfordelte.

wald testen ser hvor mange standardafvigelser der er mellem den observerede 
logodds ratio og 0. 

den estimerer vi med sqrt(1/23 + 1/117 + 1/6 + 1/210) = 0.47

log af odds ratio var 1.94. dvs sige den observerede logodds ratio er 1.93/0.47 = 4.11

Tommelfinger reglen er at hvad som helst der ligger mere edn to standardafvigelser
fra middelværdien har en p-værdi mindre end 0.05. Så den er signifikant.

en præcis to-sidet p-værdi får vi ved at beregne arealet under normalfordelingen
over 1.93 og under -1.93.

p-værdien er ret lille.





Hvis du mener at odds for at FCK vinder en given kamp er 1,7, betyder det at 
