---
title: "Tidymodels"
author: "Christian Knudsen"
date: "21/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Statistisk analyse

Correlation and regression fundamentals with tidy data principles
K-means clustering with tidy data principles
Bootstrap resampling and tidy regression models
Hypothesis testing using resampling and tidy data
Statistical analysis of contingency tables
   
Lave robuste modeller

REGRESSION MODELS TWO WAYS
CLASSIFICATION MODELS USING A NEURAL NETWORK
SUBSAMPLING FOR CLASS IMBALANCES
MODELING TIME SERIES WITH TIDY RESAMPLING
WORKING WITH MODEL COEFFICIENTS
MULTIVARIATE ANALYSIS USING PARTIAL LEAST SQUARES

Tune, compare and work with models

MODEL TUNING VIA GRID SEARCH
NESTED RESAMPLING
ITERATIVE BAYESIAN OPTIMIZATION OF A CLASSIFICATION MODEL
TUNING TEXT MODELS

Udvikle egne modeller
CREATE YOUR OWN RECIPE STEP FUNCTION
HOW TO BUILD A PARSNIP MODEL
CUSTOM PERFORMANCE METRICS
HOW TO CREATE A TUNING PARAMETER FUNCTION
CREATE YOUR OWN BROOM TIDIER METHODS
